Add multiple features
BHoM/PowerPoint_Toolkit pull request #21
Opened 2024-06-27 09:55 UTC by IsakNaslundBh

### Issues addressed by this PR

Closes #15

### Test files

### Changelog

- Add ability to replace polyline figure
- Add ability to replace image via stream
- Add Multiline text update
- Add ability to control shape fill and outline
- add ability to control text colour

### Additional comments

2024-06-27 14:05 UTC, Tom-Kingstone requested changes, later dismissed
A few changes, `using` should be used wherever streams are created that need closing

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_oM/MultiLineTextUpdate.cs
> +        public virtual string Colour { get; set; } = "";
For colour, would it not be better to use `System.Drawing.Color`? I don't know if there are any useful helper methods for creating colours in BHoM_Engine (If not I guess it would go in Graphics_Engine). In any case, it would remove the need to validate user inputted strings into colours.

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_oM/ImageUpdateStream.cs
> +        [Description("File path of the new image.")]
```suggestion
        [Description("Stream containing the new image.")]
```

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_oM/ImageUpdateStream.cs
> +        public virtual string ImageType { get; set; } = "";
Could an enum be used here instead?

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_oM/MultiPolylineUpdate.cs
> +    [Description("Allows to replace the image content of an image element.")]
```suggestion
    [Description("Allows to change the geometry of a shape element.")]
```

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_oM/MultiPolylineUpdate.cs
> +        [Description("Name of the image element that needs to be updated.")]
```suggestion
        [Description("Name of the shape element that needs to be updated.")]
```

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_oM/ShapeColourUpdate.cs
> +        [Description("Name of the text element that needs to be updated.")]
```suggestion
        [Description("Name of the shape element that needs to be updated.")]
```

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_Adapter/AdapterActions/Push.cs
> +                    presentationDoc.Clone(m_OutputFileSettings.GetFullFileName());
```suggestion
                    presentationDoc.Clone(m_OutputFileSettings.GetFullFileName()).Dispose();
```
This is the fix that allows scripts that use the adapter to remain open if you want to open the output presentation, as the garbage collector doesn't dispose the cloned document automatically (for some reason).

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_Adapter/AdapterActions/Push.cs
>                  memoryStream = OpenTemplateFile(m_TemplateFileSettings.GetFullFileName());
Instead of wrapping everything in a big try/catch, it would be better to wrap with a `using()`. This way if an exception occurs, any disposal of the document and memory stream would be done automatically. I have made changes to this effect on the branch for #16, so don't worry about this one too much

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_Adapter/CRUD/Update/Colour.cs
> +                .FirstOrDefault();
Seeing as this is being used so much, would it be better to make it an extension method for `SlidePart`s?

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_Adapter/CRUD/Update/Colour.cs
> +            }
```suggestion
            if (!string.IsNullOrEmpty(update.EdgeColour))
            {
                Drawing.Outline outline = shape.ShapeProperties?.GetFirstChild<Drawing.Outline>() ?? shape.ShapeProperties.AppendChild(new Drawing.Outline());
            
                SetFillColour(outline, update.EdgeColour)
            }
```
please do!

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_Adapter/CRUD/Update/Image.cs
> +            }
is it possible to use an enum?

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_Adapter/CRUD/Update/Text.cs
> +                    runs.First().Text = new Drawing.Text(fullText);
My understanding of how openxml text works, is that `TextBody` is split into `Paragraph`s, which are split into `Run`s. The way that you are inserting the text, while it produces the right result, is creating badly formed xml. I would expect for an inputted list of strings to make a new `Paragraph` for each string, rather than putting them all into one `run`. This also has the side-effect of only ever replacing the first paragraph, and leaving all the rest of the paragraphs as before.

As I understand, the runs are for if - in a paragraph - a bit of text has different properties to the rest of the paragraph (such as a different font, or italics etc.).

The following code would be more what I had in mind for this. This also fixes any ignored text:
```
// Create text body and internal properties if they do not exist.
TextBody textBody = shape.TextBody ?? shape.AppendChild(new TextBody(new Drawing.BodyProperties(), new Drawing.ListStyle()));

List<Drawing.Paragraph> paragraphs = textBody.Elements<Drawing.Paragraph>().ToList();

//create a new paragraph in the text body with the text for that paragraph in a run if it does not already exist, otherwise change 

bool updateColour = !string.IsNullOrEmpty(update.Colour);
List<Drawing.Paragraph> newParagraphs = new List<Drawing.Paragraph>();

for (int paragraphIndex = 0; paragraphIndex < update.Text.Count; paragraphIndex++)
{
    Drawing.Paragraph paragraph = (Drawing.Paragraph)paragraphs.ElementAtOrDefault(paragraphIndex)?.CloneNode(true) ?? new Drawing.Paragraph();

    Drawing.Run run = (Drawing.Run)paragraph.GetFirstChild<Drawing.Run>()?.CloneNode(true) ?? paragraph.AppendChild(new Drawing.Run());

    if (run.RunProperties != null)
        run.RunProperties.SpellingError = null;
    else
        run.RunProperties = new Drawing.RunProperties();

    if (updateColour)
        SetFillColour(run.RunProperties, update.Colour);

    paragraph.RemoveAllChildren<Drawing.Run>();
    paragraph.AddChild(run);

    Drawing.Text text = run.Text ?? run.AppendChild(new Drawing.Text());
    text.Text = update.Text[paragraphIndex];

    newParagraphs.Add(paragraph);
}

textBody.RemoveAllChildren<Drawing.Paragraph>();
textBody.Append(newParagraphs);
```

2024-06-27 14:05 UTC, Tom-Kingstone commented on PowerPoint_Adapter/CRUD/Update/_IUpdateSlide.cs
> +            }
What is the purpose of this, when stream already has a `Stream.CopyTo(Stream)`?

2024-06-28 09:28 UTC, IsakNaslundBh commented on PowerPoint_Adapter/CRUD/Update/_IUpdateSlide.cs
> +            }
This method was here before, just looks like I added it when rearanging files. I do nto think it is used anywhere, but decided to just keep it to not touch things I have not changed. WIll leave it in for now.

2024-06-28 09:29 UTC, IsakNaslundBh commented on PowerPoint_Adapter/CRUD/Update/Text.cs
> +                    runs.First().Text = new Drawing.Text(fullText);
Will have to check how this handled bullet-points. If that works, I am happy to change to this.

2024-06-28 09:30 UTC, IsakNaslundBh commented on PowerPoint_Adapter/CRUD/Update/Image.cs
> +            }
Guess so, but also some benefit of using strings when getting things out from files, just simply taking the extension.
Happy for this to be changed at a later date, but do not think it needs to happen on this PR.

2024-06-28 09:32 UTC, IsakNaslundBh commented on PowerPoint_Adapter/CRUD/Update/Colour.cs
> +                .FirstOrDefault();
Do not disagree here, thought about it as well, but have been a bit in a time scramble, and just pushed on. 
Will add a helper method for this.

2024-06-28 09:38 UTC, IsakNaslundBh commented on PowerPoint_oM/ImageUpdateStream.cs
> +        public virtual string ImageType { get; set; } = "";
Longer terms, yes, but would keep like this for now.

2024-07-10 08:38 UTC, adecler commented
@BHoMBot check code-compliance
@BHoMBot check copyright-compliance
@BHoMBot check documentation-compliance
@BHoMBot check project-compliance

2024-07-10 08:41 UTC, adecler commented
@BHoMBot fix copyright headers ref. 27257836945

2024-07-10 08:47 UTC, adecler commented
@BHoMBot check code-compliance
@BHoMBot check copyright-compliance
@BHoMBot check documentation-compliance
@BHoMBot check project-compliance

2024-07-10 08:50 UTC, adecler commented
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation
@BHoMBot check installer

2024-07-10 09:25 UTC, adecler commented
@BHoMBot check ready-to-merge

2024-07-10 09:27 UTC, adecler approved these changes
Tested and working well within the context of the FloorSystem_Tool(kit) for which this PR was made.

2024-07-10 09:29 UTC, adecler commented
@BHoMBot check versioning

2024-07-10 09:32 UTC, merged